name: "Notion to Jekyll"
description: "Synchronize Notion to Jekyll"
author: "whatasame"

branding:
  icon: "heart"
  color: "red"

inputs:
  notion_api_key:
    description: "Notion API key"
    required: true
  notion_database_id:
    description: "Notion database ID"
    required: true
  github_workspace:
    description: "Github workspace"
    required: false
    default: ${{ github.workspace }}
  github_token:
    description: "Github token"
    required: true
  post_dir:
    description: "Post directory"
    required: false
    default: "_posts"
  commit_username:
    description: "Commit username"
    required: false
    default: ${{ github.actor }}
  commit_email:
    description: "Commit email"
    required: false
    default: ${{ github.actor }}@users.noreply.github.com
  commit_author:
    description: "Commit author"
    required: false
    default: ${{ github.actor }}
  commit_message:
    description: "Commit message"
    required: false
    default: "docs: Update posts"
  repository:
    description: "Repository"
    required: false
    default: ${{ github.repository }}

runs:
  using: node20
  main: dist/index.js
