name: "Notion to Jekyll"
description: "GitHub action for synchronizing Notion to Jekyll"
author: "whatasame"

branding:
  icon: "upload-cloud"
  color: "red"

inputs:
  notion_api_key:
    description: "Notion API key"
    required: true
  notion_database_id:
    description: "Notion database ID"
    required: true
  github_workspace:
    description: "Github workspace"
    required: false
    default: ${{ github.workspace }}
  post_dir:
    description: "Post directory"
    required: false
    default: "_posts"
  post_layout:
    description: "Post layout"
    required: false
    default: "post"
  post_layout_skip:
    description: "Post layout skip"
    required: false
    default: false
  commit_username:
    description: "Commit username"
    required: false
    default: ${{ github.actor }}
  commit_email:
    description: "Commit email"
    required: false
    default: ${{ github.actor }}@users.noreply.github.com
  commit_author:
    description: "Commit author"
    required: false
    default: ${{ github.actor }}
  commit_message:
    description: "Commit message"
    required: false
    default: "Synchronized by Notion to Jekyll"
  repository:
    description: "Repository"
    required: false
    default: ${{ github.repository }}

runs:
  using: node20
  main: dist/index.js
