name: Continuous Integration

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm

      - run: npm ci
      - run: npm run coverage && npm run pacakge

      - uses: EndBug/add-and-commit@v7
        with:
          add: '[ "dist", "badges" ]'
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: "chore: Update dist"
