on:
  workflow_dispatch:

jobs:
  local-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test local action
        id: test-action
        uses: ./

      - name: Check if '__post' directory exists
        id: check-post-directory
        run: |
          if [ -d "__post" ]; then
            echo "Success: '__post' directory exists."
          else
            echo "Error: '__post' directory not found."
            exit 1
          fi
