on:
  workflow_dispatch:

jobs:
  local-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test action locally
        uses: ./
        with:
          notion_api_key: ${{ secrets.NOTION_API_KEY }}
          notion_database_id: ${{ secrets.NOTION_DATABASE_ID }}

      - name: Check if '__post' directory exists
        run: |
          if [ -d "__posts" ]; then
            echo "Success: '__post' directory exists."
          else
            echo "Error: '__post' directory not found."
            exit 1
          fi
