on:
  workflow_dispatch:

jobs:
  local-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test action locally
        uses: ./
        with:
          notion_api_key: ${{ secrets.NOTION_API_KEY }}
          notion_database_id: ${{ secrets.NOTION_DATABASE_ID }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if '_post' directory exists
        run: |
          if [ -d "_posts" ]; then
            echo "Success: '_post' directory exists."
          else
            echo "Error: '_post' directory not found."
            exit 1
          fi
